theme: jekyll-theme-cayman
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
docs_list_title: ACME Documentation
docs:
- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html
